#!/bin/bash

export GPG_TTY=$(tty)
git commit -S -m "$1"
CURRENT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
if [ $CURRENT_BRANCH == "master" ] 
then 
echo "Master!"
else
echo "DUH"
fi

git push origin $CURRENT_BRANCH
